name: Check Last Commit Time

on:
  workflow_dispatch:
  schedule:
      - cron:  '0 1 * * *'

jobs:
  main:
    runs-on: ubuntu-20.04
    steps:
      - name: Fetch periscope/master branch
        uses: actions/checkout@v3
        with:
          repository: Moneylion/de-periscope-2nd
          token: ${{ secrets.PAT__DE_PERISCOPE_2ND }}
          ref: periscope/master
          fetch-depth: 1

      - name: Check for commits within time
        uses: AlexHolderDeveloper/CommitsWithinTime@v1.1.5
        id: commitswithintime
        with:
          hours: 24

      - name: Get the output from CommitsWithinTime
        run: |
          echo "The 'has-new-commits-within-time' value is ${{ steps.commitswithintime.outputs.has-new-commits-within-time }}"
          echo "The 'number-of-commits-within-time' value is ${{ steps.commitswithintime.outputs.number-of-commits-within-time }}"
          echo "The 'total-commits' value is ${{ steps.commitswithintime.outputs.total-commits }}"
