name: Check Last Commit Time

on:
  workflow_dispatch:
  schedule:
      - cron:  '0 1 * * *'

jobs:
  main:
    runs-on: ubuntu-20.04
    steps:
      - name: Fetch periscope/master branch
        uses: actions/checkout@v3
        with:
          repository: Moneylion/de-periscope-2nd
          token: ${{ secrets.PAT__DE_PERISCOPE_2ND }}
          ref: periscope/master
          fetch-depth: 25

      - name: Check for commits within time
        uses: AlexHolderDeveloper/CommitsWithinTime@v1.1.5
        id: commitswithintime
        with:
          hours: 24
          usernamesToFocus: '{"allowedUsernamesList": ["Periscope Data"]}'
          

      - name: Get the output from CommitsWithinTime
        run: |
          echo "The 'has-new-commits-within-time' value is ${{ steps.commitswithintime.outputs.has-new-commits-within-time }}"
          echo "The 'number-of-commits-within-time' value is ${{ steps.commitswithintime.outputs.number-of-commits-within-time }}"
          echo "The 'total-commits' value is ${{ steps.commitswithintime.outputs.total-commits }}"

      - name: Slack Notification
        uses: ravsamhq/notify-slack-action@v2
        if: ${{ steps.commitswithintime.outputs.has-new-commits-within-time }} == 'true'
        with:
          status: ${{ job.status }}
          notification_title: "Repo updated within last 24 hours"
          message_format: "Beep"
          # footer: "Linked Repo <{repo_url}|{repo}> | <{workflow_url}|View Workflow> | <{run_url} |View Run>"
          notify_when: "success"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
